CREATE TABLE IF NOT EXISTS llm_sandbox.voice_to_soap.feedback_ingest (
  feedback_id STRING,
  tracking_id STRING,
  trace_id STRING,
  site_id STRING,
  user_id STRING,
  pims_id STRING,
  pims STRING,
  feedback_boolean BOOLEAN,
  feedback_score_1 DOUBLE,
  feedback_score_2 DOUBLE,
  feedback_comment_1 STRING,
  feedback_comment_2 STRING,
  timestamp TIMESTAMP,
  schema_version STRING,
  ingested_at TIMESTAMP,
  source_app STRING,
  service_name STRING,
  consumer_id STRING,
  request_id STRING,
  payload_hash STRING,
  link_mode STRING,
  link_target_trace_id STRING,
  link_window_seconds INT,
  link_match_count INT,
  link_reason STRING,
  auth_subject STRING,
  auth_scopes STRING,
  is_valid BOOLEAN,
  validation_errors ARRAY<STRING>
)
USING DELTA
CLUSTER BY (ingested_at, tracking_id, trace_id, payload_hash);